apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: wp
  replicas: 1
  template:
    metadata:
      labels:
        app: wp
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom: 
                secretKeyRef:
                  name: wp-secret
                  key: WORDPRESS_DB_HOST 
            - name: WORDPRESS_DB_USER
              valueFrom: 
                secretKeyRef:
                  name: wp-secret
                  key: WORDPRESS_DB_USER 
            - name: WORDPRESS_DB_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: wp-secret
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom: 
                secretKeyRef:
                  name: wp-secret
                  key: WORDPRESS_DB_NAME
          volumeMounts:
            - name: data-wp-volume
              mountPath: /var/www/html/
      volumes:
        - name: data-wp-volume
          hostPath:
            path: /data/wordpress
            type: Directory



