apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/CKA/postgresql
    server: 10.10.10.1 # <= PUT YOUR NFS-SERVER IP
