apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: icgroup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      environment: prod
  template:
    metadata:
      labels:
        app: webapp
        environment: prod
    spec:
      containers:
        - name: webapp
          image: erickmpene/ic-group:v1
          resources:
            limits:
              memory: "700Mi"
              cpu: "500m"
          env:
          - name: ODOO_URL
            value: http://$(HOST_IP):32700
          - name: PGADMIN_URL
            value: http://$(HOST_IP):32701
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data-webapp
              mountPath: /opt
      volumes: 
        - name: data-webapp
          persistentVolumeClaim: 
            claimName: pvc-webapp



