apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-odoo-data-data
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/CKA/odoo/data
    server: 10.10.10.10 # <= PUT YOUR NFS-SERVER IP


--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-odoo-data-config
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/CKA/odoo/config
    server: 10.10.10.10 # <= PUT YOUR NFS-SERVER IP

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-odoo-data-addons
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/CKA/odoo/addons
    server: 10.10.10.10 # <= PUT YOUR NFS-SERVER IP