apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-data-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-data-config
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 700Mi


--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-odoo-data-addons
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi