apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
type: Opaque 
stringData:
  WORDPRESS_DB_HOST: mysql-service
  WORDPRESS_DB_USER: wp_user
  WORDPRESS_DB_PASSWORD: MyPassWord
  WORDPRESS_DB_NAME: wordpress

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque 
stringData:
  MYSQL_ROOT_PASSWORD: Root_PassWord 
  MYSQL_DATABASE: wordpress 
  MYSQL_USER: wp_user
  MYSQL_PASSWORD: MyPassWord

