apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pgadmin
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/CKA/pgadmin/pgadmin
    server: 10.10.10.10 # <= PUT YOUR NFS-SERVER IP


--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pgadmin4
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/CKA/pgadmin/pgadmin4
    server: 10.10.10.10 # <= PUT YOUR NFS-SERVER IP

